language: cpp
compiler: 
    - clang
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get upgrade -y
    - sudo apt-get install julia -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e "Pkg.init()"
    - julia -e "Pkg.add(\"GZip\")"
    - mkdir -p ~/.julia/FastaRead
    - cp -R ./* ~/.julia/FastaRead/
    - julia ~/.julia/FastaRead/test/test.jl
branch:
    except:
        - release-0.1
